# Generated by Django 2.2.4 on 2019-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190916_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smellsensor',
            name='level_smellsensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='soapsensor',
            name='level_soapsensor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tissuesensor',
            name='level_tissuesensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
