# Generated by Django 2.2.4 on 2019-08-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190827_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smellsensor',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AlterField(
            model_name='soupsensor',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AlterField(
            model_name='tissuesensor',
            name='empty_reading',
            field=models.CharField(default='10', max_length=255),
        ),
    ]
