# Generated by Django 2.2.4 on 2019-09-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190917_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapsensor',
            name='initial_reading',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
